run:
  skip-dirs:
    - internal/ucd
    - internal/gen
    - internal/phash
linters:
  enable:
    - misspell
    - goimports
    - gofmt
    - gocheckcompilerdirectives
output:
  sort-results: true
issues:
  exclude-rules:
    - path: internal/bytealg/index_amd64.go
      text: "constant visible only to assembly"
      linters:
        - unused
  fix: false
