version: "2"
linters:
  enable:
    - gocheckcompilerdirectives
    - mirror
    - misspell
    - unconvert
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - gen/gen
      - gen/ucd
      - ^gen$
      - ^ucd$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 100
  max-same-issues: 100
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - gen/gen
      - gen/ucd
      - ^gen$
      - ^ucd$
      - third_party$
      - builtin$
      - examples$
