# We only run the "release" test on the latest version
# of Go since it is slow.
---
name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.x'

    - name: Test Core
      run: make codecov

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Test
      run: make testgenpkg testgenerate testbenchmarks testskipped calibrate vet
