---
name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19', '1.20', '1.21.x', '1.22.x', '1.23.x']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        name: Cache unicode
        with:
          path: ${{ github.workspace }}/internal/gen/gentables/DATA
          key: ${{ runner.os }}-data-${{ hashFiles('${{ github.workspace }}/**/*.txt') }}

      # Cache richgo and golangci-lint
      - uses: actions/cache@v4
        name: Cache bin
        with:
          path: bin
          # The Makefile sets the version of richgo and golangci-lint
          key: ${{ runner.os }}-bin-${{ hashFiles('${{ github.workspace }}/common.mk') }}

      - uses: actions/setup-go@v5
        name: Setup Go ${{ matrix.go-version }}
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: make ci --jobs=$(nproc)

      - name: Test Skipped
        run: make testskipped
